### ISSUE TITLE
Crash using wildlife and mobkit

### ISSUE THREAD

**Issue by dethegeek** [TheTermos/wildlife#3]
Hi

I just experienced a crash ingame. The player was digging when it happened. I cannot reproduce easily for now, but I hope the backtrace will help to solve the bug (either in mobkit, either in wildlife).

The crash occured with the development version of Minetest (5.2.0-dev-f7c7353a), compiled a few days ago from sources.

```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'wildlife' in callback luaentity_Step(): .../software/minetest/bin/../mods/mobkit/init.lua:167: table index is nil
stack traceback:
	.../software/minetest/bin/../mods/mobkit/init.lua:167: in function 'get_nodes_in_area'
	.../software/minetest/bin/../mods/wildlife/init.lua:21: in function 'lava_dmg'
	.../software/minetest/bin/../mods/wildlife/init.lua:28: in function 'logic'
	.../software/minetest/bin/../mods/mobkit/init.lua:940: in function <...bugier/software/minetest/bin/../mods/mobkit/init.lua:921>
```

EDIT : When trying to resume the game, minetest failed to load the world. I joined the game (locally) then immediately crashed with the same backtrace. I succeeded to load the game by re-enabling an other mod I disabled a few hours ago : dmobs. As there are some unknown nodes left in the workd after disabliing horror (https://github.com/D00Med/horror), maybe there is a relation witrh the crash I encouteered.

**Comment by TheTermos** [comment]
> As there are some unknown nodes left in the workd after disabliing horror (https://github.com/D00Med/horror), maybe there is a relation witrh the crash I encouteered.

That's definitely it, I'm on it.

**Comment by TheTermos** [comment]
The fix is in mobkit 'dev' branch (not wildlife). Can you try it and see if it solves the issue?
https://github.com/TheTermos/mobkit/tree/dev

**Comment by dethegeek** [comment]
Hi

Thanks, I'll test it. However, I could not find an accurate way to reproduce, then I will install then disable the Horror mod, and try to walk near unknown nodes several times.

**Comment by dethegeek** [comment]
I still have the world where the bug occured. I walked around the place where I was when the game crashed. No problem so far. 

As the patch makes sense, I think it is OK.

**Comment by TheTermos** [comment]
Done a proper test involving dropping animals onto plantlike nodes and disabling them, seems to work, closing.
